#! /bin/sh
#
# skeleton      example file to build /etc/init.d/ scripts.
#               This file should be used to construct scripts for /etc/init.d.
#
# Author:       Miquel van Smoorenburg <miquels@cistron.nl>.
#               Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
#               You may remove the "Author" lines above and replace them
#               with your own name if you copy and modify this script.
#
# Version:      @(#)skeleton  1.9.3  02-Nov-2003  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/ubuntu/p1_computacion/flask run
NAME=flask
DESC="flask daemon"

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
#[ -r /etc/default/$NAME ] && . /etc/default/$NAME

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
        start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/$NAME.pid \
        	--background --exec $DAEMON
	echo "."
	;;
  stop)
        echo -n "Stopping $DESC: $NAME "
        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
        --exec $DAEMON
        echo "."
        ;;
	#reload)
        #
        #       If the daemon can reload its config files on the fly
        #       for example by sending it SIGHUP, do it here.
        #
        #       If the daemon responds to changes in its config file
        #       directly anyway, make this a do-nothing entry.
        #
        # echo -n "Reloading $DESC configuration..."
        # start-stop-daemon --stop --signal 1 --quiet --pidfile \
        #       /var/run/$NAME.pid --exec $DAEMON
        # echo "done."
  #;;
  restart|force-reload)
        #
        #       If the "reload" option is implemented, move the "force-reload"
        #       option to the "reload" entry above. If not, "force-reload" is
        #       just the same as "restart".
        #
        echo -n "Restarting $DESC: $NAME"
        start-stop-daemon --stop --quiet --pidfile \
              /var/run/$NAME.pid --exec $DAEMON
        sleep 1
        start-stop-daemon --start --quiet --pidfile \
              /var/run/$NAME.pid --exec $DAEMON
        echo "."
        ;;
  *)
esac

exit 0

